import Head from "next/head";

import { Home } from "./home";
import { TopBar } from "@/shared/components/TopBar";
import { DataProps } from "@/shared/types/DataProps";
import { Footer } from "@/shared/components/Footer";
import { Dispatch, SetStateAction, createContext, useState } from "react";
import { WorkProps } from "@/shared/types/WorkProps";

interface ContextProps {
  dataSearched: WorkProps[];
  setDataSearched: Dispatch<SetStateAction<WorkProps[]>>;
}

export const Context = createContext<ContextProps>({
  dataSearched: [],
  setDataSearched: () => {},
});

export async function getServerSideProps() {
  // Latest data request
  const reqAllData = await fetch(
    "https://collectionapi.metmuseum.org/public/collection/v1/search?q=latest added"
  );
  const allData = await reqAllData.json();
  const latestDataPromises = await allData.objectIDs
    .slice(0, 12)
    .map((id: number) =>
      fetch(
        `https://collectionapi.metmuseum.org/public/collection/v1/objects/${id}`
      )
    );

  const latestDataResponses = await Promise.all(latestDataPromises);
  const latestData = await Promise.all(
    latestDataResponses.map((response) => response.json())
  );

  return { props: {  latestData } };
}

export default function Index({  latestData }: DataProps) {
  const [dataSearched, setDataSearched] = useState<WorkProps[]>([]);

  return (
    <Context.Provider value={{ dataSearched, setDataSearched }}>
      <Head>
        <title>Metropolitan Museum Of Art</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main>
        <TopBar />
        <Home latestData={latestData} />
        <Footer />
      </main>
    </Context.Provider>
  );
}
