import Head from "next/head";
import dayjs from "dayjs";

import { Home } from "./home";
import { TopBar } from "@/shared/components/TopBar";
import { DataProps } from "@/shared/types/DataProps";
import { Footer } from "@/shared/components/Footer";

export async function getServerSideProps() {
  const today = dayjs();
  const currentDate = today.format("YYYY-MM-DD");

  // Today data request
  const reqTodayData = await fetch(
    `https://collectionapi.metmuseum.org/public/collection/v1/objects?metadataDate=${currentDate}`
  );
  const todayDataResponse = await reqTodayData.json();
  const todayDataPromisses = await todayDataResponse.objectIDs.map(
    (id: number) =>
      fetch(
        `https://collectionapi.metmuseum.org/public/collection/v1/objects/${id}`
      )
  );

  const todayDataResponses = await Promise.all(todayDataPromisses);
  const todayData = await Promise.all(
    todayDataResponses.map((response) => response.json())
  );

  // Latest data request
  const reqAllData = await fetch(
    "https://collectionapi.metmuseum.org/public/collection/v1/search?q=latest added"
  );
  const allData = await reqAllData.json();
  const latestDataPromises = await allData.objectIDs
    .slice(0, 9)
    .map((id: number) =>
      fetch(
        `https://collectionapi.metmuseum.org/public/collection/v1/objects/${id}`
      )
    );

  const latestDataResponses = await Promise.all(latestDataPromises);
  const latestData = await Promise.all(
    latestDataResponses.map((response) => response.json())
  );

  return { props: { todayData, latestData } };
}

export default function Index({ todayData, latestData }: DataProps) {
  return (
    <>
      <Head>
        <title>Metropolitan Museum Of Art</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main>
        <TopBar />
        <Home todayData={todayData} latestData={latestData} />
        <Footer />
      </main>
    </>
  );
}
